default: &default
    class: 'Patch2PixRefined'
    ckpt: 'pretrained/patch2pix/patch2pix_pretrained.pth'
    imsize: 1024
coarse_default: &coarse_default
    name: 'SuperGlue'
    weights: 'outdoor'    
    sinkhorn_iterations: 50
    max_keypoints: 4096
    nms_radius: 4
    imsize: 1024
sat:
    <<: *default
    class: 'Patch2Pix'
    no_match_upscale: True
    ksize: 2
    match_threshold: 0.15
    coarse:
        <<: *coarse_default
        match_threshold: 0.1
inloc:
    <<: *default
    match_threshold: 0.1
    imsize: 1600 
    pairs: 'pairs-query-netvlad40-temporal.txt' 
    rthres: 48
    skip_matches: 20 
    coarse:
        <<: *coarse_default
        match_threshold: 0.1
        imsize: 1600
aachen:
    <<: *default
    match_threshold: 0.0 # Save all matches
    pairs: ['pairs-db-covis20.txt', 'pairs-query-netvlad50.txt']
    qt_dthres: 4
    qt_psize: 48
    qt_unique: True
    ransac_thres: [20]
    sc_thres: 0.25 # Filtering during quantization
    covis_cluster: False
    coarse:
        <<: *coarse_default
        match_threshold: 0.1
aachen_v1.1:
    <<: *default
    match_threshold: 0.0 # Save all matches
    pairs: ['pairs-db-covis20.txt', 'pairs-query-netvlad50.txt']
    qt_dthres: 4
    qt_psize: 48
    qt_unique: True
    ransac_thres: [20]
    sc_thres: 0.25 # Filtering during quantization
    covis_cluster: True
    coarse:
        <<: *coarse_default
        match_threshold: 0.1
